[package]
name = "joshuaclarkelua/component"
description = "Component class"
version = "3.0.3"
license = "MIT"
authors = ["Joshua Clarke", "Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include=["src", "default.project.json"]

[dependencies]
Signal = "sleitnick/signal@^2"
Symbol = "sleitnick/symbol@^2"
Trove = "sleitnick/trove@^1"
Promise = "joshuaclarkelua/promise@^4"
Knit = "joshuaclarkelua/knit@^1"
