[package]
name = "joshuaclarkelua/trove"
description = "Trove class for tracking and cleaning up objects"
version = "1.4.2"
license = "MIT"
authors = ["Stephen Leitnick", "Joshua Clarke"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
