[package]
name = "joshuaclarkelua/comm"
description = "(FORKED) Comm library for remote communication"
version = "1.0.2"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2"
Option = "sleitnick/option@1"
Promise = "joshuaclarkelua/promise@^4"
